# (PART) Part One {-} 

# Introduction {#intro}

## Todo
Come back to this when the rest is done. 

## What's in this class, anyway?
 This book assumes that you have no background in either statistics or programming (but it will come in handy if you do). It's designed to give you an introduction to programming with the R language, to teach you the basic principles behind statistics and machine learning, and to get you comfortable working with, analyzing, and visualizing data yourself. Along the way, there will be continual applications to real-world uses of data science in global health, business, biology, and other fields. 


## Course Layout
Please carefully read the course syllabus for a full rundown of the class. (Don't forget to scroll down to the section on hate speech, that one's important.)

The course is split into modules like this one, each of which has several pages you should read through, and occasionally associated readings, discussions, and assignments. Almost every module will also have a quiz at the end. This module, for example, has two pages, one assignment (the essay), one reading (the syllabus),  and one quiz. 

All input from you is due on Sundays-- quizzes and discussion responses must be in by midnight on the Sunday after the module (or section of module) is opened, assignments are due one week later (with the exception of Essay #2 and the final project).

Note that not all modules are the same length-- this week, for example, there are two modules, whereas module 8 is split into three one-week chunks. Modules are organized by content, not time.   

In addition to the discussion boards associated with readings, there are also a few special discussion boards for asking questions or posting interesting data-science related finds.

 

## Discussions
Most of you are already quite familiar with discussion participation in online classes, but here's the rundown:

--Please do the reading before posting to the board.

--If you have something interesting to say, don't be limited by the prompts given.

--Post at least twice over the course of the week to receive full credit; and by "post", I mean "add meaningfully to the conversation". Lone smiley face emojis are not valid "posts".

--This may be new to some of you: Posts are "threaded", so you can reply to people's responses and start cohesive conversations, and I've enabled "liking" on posts-- that means that if a bunch of people "like" a specific post or thread, it will show up at the top of the page for easy access (this is the same system that Reddit uses, if you're familiar). Please "like" the posts/threads that are particularly useful to you! The system doesn't work if you don't use it.

--Shrawan and I will actively browse in (and, when appropriate, contribute to) discussion boards.

 

## Special Discussions
There are a few discussion sections that aren't like the others. These are specifically designed for people to share data-science related items, or to ask for help. See specific descriptions below.

General Course Questions/Comments: Just what it sounds like. If you have any questions or concerns about the course as a whole that you don't mind sharing publicly and anonymously, please post them here. If you'd like to raise a question/concern with me privately, email me. If you'd like to be private and anonymous, post it to the course feedback google form. 

Data Science in the World: See a cool use of data science in your news feed? Post it here! People are doing incredible things with data science all the time, and I can't keep track of it all. I'll be posting a lot of data visualizations here, hopefully at least one or two a week. 

Coding Questions: Are you banging your head against a wall because your code won't work? Ask your question here! Your peers, Shrawan, and I should be able to help you. However, this thread should not be the first place you go if you're stuck. Your process should look like this:

Google/check StackOverflow for an answer to your question (this will be covered further in Module 4)
Post to the discussion board
Email me/Shrawan
Post your own StackOverflow question
Please be sure to adhere to the posting guidelines outlined in the discussion body to make sure your question is as clear as possible. 

Statistics Questions: Same idea as the coding questions thread, but for stats questions. Same guidelines apply. 

NOTE: Students who are already familiar with programming/statistics are strongly encouraged to help their peers solve problems on this thread. Help each other! 

 

## Additional Readings
 There will be a handful of readings that don't have a discussion associated with them, but which will be extremely valuable to your understanding of the course. If a reading has a "*" next to it, that means I ask questions about it in a quiz or problem set. If it doesn't have a star, you should read it anyway, but there's no grading penalty if you don't. 

 

